trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: destroy_stage
  displayName: terraform stage
  jobs:
  - job: destroy_job
    displayName: terraform job
    steps:
    - task: TerraformInstaller@1
      displayName: terraform install
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: terraform init
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/aws'
        backendServiceAWS: 'aws-eu-west-1'
        backendAWSBucketName: 'uniquename'
        backendAWSKey: 'tf/terraform.tfstate'
    - task: TerraformTaskV4@4
      displayName: terraform destroy
      inputs:
        provider: 'aws'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)/aws'
        environmentServiceNameAWS: 'aws-eu-west-1'